import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// A single autogenerated sidebar. Chapters are numbered NN-slug.md so the
// autogenerated order matches the intended reading order.
const sidebars: SidebarsConfig = {
  courseSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
